### ISSUE TITLE
Vararg functions

### ISSUE THREAD

**Issue by gmoutsin** [JuliaCollections/Memoize.jl#40] opened 2019-10-26 13:41 UTC
```
@memoize function test(a::Vararg{Int})
    return length(a)
end

test(1,2)
```

gives

`TypeError: test: in typeassert, expected Vararg{Int64,N} where N, got Tuple{Int64,Int64}`

I guess the problem is that `Tuple{Int64,Int64}` is not considered a subtype of `Vararg{Int64,N} where N`. I appreciate this is probably a problem that can only be solved by changing the type system, but I thought I should report it here too.

**Comment by kmsquire** [comment] 2020-02-19 01:37
Duplicate of #26 (which @gmoutsin also opened).

Memoize.jl has been mostly unmaintained the last few years.  I just started poking at it (because I wanted to use it).  No promises, but I'll see what I can do unless/until someone else steps up (which seems somewhat unlikely).

**Closed by kmsquire** 2020-02-19 01:37 UTC
