### ISSUE TITLE
UndefVarError: Inference not defined

### ISSUE THREAD

**Issue by gpapo** [JuliaCollections/Memoize.jl#27] opened 2018-06-08 14:54 UTC
On Julia v0.7-alpha (I omitted deprecation warnings); it doesn't work even using the latest version of the package.

```julia
julia> using Memoize

julia> @memoize f(x) = x <= 1 ? 1 : x * f(x - 1)
f (generic function with 1 method)

julia> f(23)
8128291617894825984

julia> f(5)
ERROR: UndefVarError: Inference not defined
Stacktrace:
 [1] f(::Int64) at /home/giovanni/.julia/packages/Memoize/QPoI/src/Memoize.jl:109
 [2] top-level scope

```

**Comment by Element-126** [comment] 2018-06-26 20:45
I believe this is caused by `Core.Inference` having been [refactored into multiple files](https://github.com/JuliaLang/julia/commit/aea91558d3b60bf6d2bcdbd608b369e28ffffc9f) in 0.7.

On Julia 0.7 beta:
```julia
julia> using Core.Inference
ERROR: UndefVarError: Inference not defined
```
but it works as expected on 0.6.3.

Interpolations.jl had the same issue (see [#197](https://github.com/JuliaMath/Interpolations.jl/pull/197)), and fixed it by replacing `Core.Inference.return_type` by `Base.promote_op` (see [the diff](https://github.com/JuliaMath/Interpolations.jl/pull/197/files)). I believe the same fix should work here as well.

A more direct fix would be to simply replace the call to `Core.Inference.return_type` by `Core.Compiler.return_type`, however I am not sure whether using `Core.Compiler` is recommended for packages.

**Comment by kmsquire** [comment] 2020-02-19 01:24
This is fixed on master.

**Closed by kmsquire** 2020-02-19 01:24 UTC
